const VAT_CONFIG = {
  regions: [
    {
      id: 'eu',
      name: 'European Union',
      countries: [
        { code: 'AT', name: 'Austria', rate: 20, currency: '€' },
        { code: 'BE', name: 'Belgium', rate: 21, currency: '€' },
        { code: 'BG', name: 'Bulgaria', rate: 20, currency: 'лв' },
        { code: 'HR', name: 'Croatia', rate: 25, currency: '€' },
        { code: 'CY', name: 'Cyprus', rate: 19, currency: '€' },
        { code: 'CZ', name: 'Czech Republic', rate: 21, currency: 'Kč' },
        { code: 'DK', name: 'Denmark', rate: 25, currency: 'kr' },
        { code: 'EE', name: 'Estonia', rate: 24, currency: '€' },
        { code: 'FI', name: 'Finland', rate: 25.5, currency: '€' },
        { code: 'FR', name: 'France', rate: 20, currency: '€' },
        { code: 'DE', name: 'Germany', rate: 19, currency: '€' },
        { code: 'GR', name: 'Greece', rate: 24, currency: '€' },
        { code: 'HU', name: 'Hungary', rate: 27, currency: 'Ft' },
        { code: 'IE', name: 'Ireland', rate: 23, currency: '€' },
        { code: 'IT', name: 'Italy', rate: 22, currency: '€' },
        { code: 'LV', name: 'Latvia', rate: 21, currency: '€' },
        { code: 'LT', name: 'Lithuania', rate: 21, currency: '€' },
        { code: 'LU', name: 'Luxembourg', rate: 17, currency: '€' },
        { code: 'MT', name: 'Malta', rate: 18, currency: '€' },
        { code: 'NL', name: 'Netherlands', rate: 21, currency: '€' },
        { code: 'PL', name: 'Poland', rate: 23, currency: 'zł' },
        { code: 'PT', name: 'Portugal', rate: 23, currency: '€' },
        { code: 'RO', name: 'Romania', rate: 19, currency: 'lei' },
        { code: 'SK', name: 'Slovakia', rate: 20, currency: '€' },
        { code: 'SI', name: 'Slovenia', rate: 22, currency: '€' },
        { code: 'ES', name: 'Spain', rate: 21, currency: '€' },
        { code: 'SE', name: 'Sweden', rate: 25, currency: 'kr' }
      ]
    },
    {
      id: 'europe-other',
      name: 'Other EU',
      countries: [
        { code: 'AL', name: 'Albania', rate: 20, currency: 'ALL' },
        { code: 'AD', name: 'Andorra', rate: 4.5, currency: '€' },
        { code: 'BY', name: 'Belarus', rate: 20, currency: 'Br' },
        { code: 'BA', name: 'Bosnia & Herzegovina', rate: 17, currency: 'BAM' },
        { code: 'IS', name: 'Iceland', rate: 24, currency: 'kr' },
        { code: 'LI', name: 'Liechtenstein', rate: 8.1, currency: 'CHF' },
        { code: 'MD', name: 'Moldova', rate: 20, currency: 'MDL' },
        { code: 'MC', name: 'Monaco', rate: 20, currency: '€' },
        { code: 'ME', name: 'Montenegro', rate: 21, currency: '€' },
        { code: 'MK', name: 'North Macedonia', rate: 18, currency: 'MKD' },
        { code: 'NO', name: 'Norway', rate: 25, currency: 'kr' },
        { code: 'RU', name: 'Russia', rate: 22, currency: '₽' },
        { code: 'RS', name: 'Serbia', rate: 20, currency: 'RSD' },
        { code: 'CH', name: 'Switzerland', rate: 8.1, currency: 'CHF' },
        { code: 'TR', name: 'Turkey', rate: 20, currency: '₺' },
        { code: 'UA', name: 'Ukraine', rate: 20, currency: '₴' },
        { code: 'GB', name: 'United Kingdom', rate: 20, currency: '£' }
      ]
    },
    {
      id: 'asia',
      name: 'Asia',
      countries: [
        { code: 'CN', name: 'China', rate: 13, currency: '¥' },
        { code: 'JP', name: 'Japan', rate: 10, currency: '¥' },
        { code: 'KR', name: 'South Korea', rate: 10, currency: '₩' },
        { code: 'TW', name: 'Taiwan', rate: 5, currency: 'NT$' },
        { code: 'BD', name: 'Bangladesh', rate: 15, currency: '৳' },
        { code: 'BT', name: 'Bhutan', rate: 7, currency: 'Nu.' },
        { code: 'IN', name: 'India', rate: 18, currency: '₹' },
        { code: 'NP', name: 'Nepal', rate: 13, currency: 'रू' },
        { code: 'PK', name: 'Pakistan', rate: 18, currency: '₨' },
        { code: 'LK', name: 'Sri Lanka', rate: 18, currency: '₨' },
        { code: 'KH', name: 'Cambodia', rate: 10, currency: '៛' },
        { code: 'ID', name: 'Indonesia', rate: 11, currency: 'Rp' },
        { code: 'LA', name: 'Laos', rate: 10, currency: '₭' },
        { code: 'PH', name: 'Philippines', rate: 12, currency: '₱' },
        { code: 'SG', name: 'Singapore', rate: 9, currency: 'S$' },
        { code: 'TH', name: 'Thailand', rate: 7, currency: '฿' },
        { code: 'VN', name: 'Vietnam', rate: 8, currency: '₫' },
        { code: 'KZ', name: 'Kazakhstan', rate: 12, currency: '₸' },
        { code: 'TJ', name: 'Tajikistan', rate: 14, currency: 'сом' },
        { code: 'UZ', name: 'Uzbekistan', rate: 12, currency: 'so\'m' }
      ]
    },
    {
      id: 'americas',
      name: 'Americas',
      countries: [
        { code: 'CA', name: 'Canada', rate: 5, currency: '$' },
        { code: 'MX', name: 'Mexico', rate: 16, currency: '$' },
        { code: 'BB', name: 'Barbados', rate: 17.5, currency: '$' },
        { code: 'BZ', name: 'Belize', rate: 12.5, currency: '$' },
        { code: 'CR', name: 'Costa Rica', rate: 13, currency: '₡' },
        { code: 'DO', name: 'Dominican Republic', rate: 18, currency: '$' },
        { code: 'SV', name: 'El Salvador', rate: 13, currency: '$' },
        { code: 'GT', name: 'Guatemala', rate: 12, currency: 'Q' },
        { code: 'HT', name: 'Haiti', rate: 10, currency: 'G' },
        { code: 'HN', name: 'Honduras', rate: 15, currency: 'L' },
        { code: 'JM', name: 'Jamaica', rate: 15, currency: '$' },
        { code: 'NI', name: 'Nicaragua', rate: 15, currency: 'C$' },
        { code: 'PA', name: 'Panama', rate: 7, currency: 'B/.' },
        { code: 'TT', name: 'Trinidad & Tobago', rate: 12.5, currency: '$' },
        { code: 'AR', name: 'Argentina', rate: 21, currency: '$' },
        { code: 'BO', name: 'Bolivia', rate: 13, currency: 'Bs.' },
        { code: 'BR', name: 'Brazil', rate: 17.5, currency: 'R$' },
        { code: 'CL', name: 'Chile', rate: 19, currency: '$' },
        { code: 'CO', name: 'Colombia', rate: 19, currency: '$' },
        { code: 'EC', name: 'Ecuador', rate: 12, currency: '$' },
        { code: 'GY', name: 'Guyana', rate: 14, currency: '$' },
        { code: 'PY', name: 'Paraguay', rate: 10, currency: '₲' },
        { code: 'PE', name: 'Peru', rate: 18, currency: 'S/' },
        { code: 'UY', name: 'Uruguay', rate: 22, currency: '$' },
        { code: 'VE', name: 'Venezuela', rate: 16, currency: 'Bs.' }
      ]
    },
    {
      id: 'africa',
      name: 'Africa',
      countries: [
        { code: 'DZ', name: 'Algeria', rate: 19, currency: 'د.ج' },
        { code: 'AO', name: 'Angola', rate: 14, currency: 'Kz' },
        { code: 'BW', name: 'Botswana', rate: 14, currency: 'P' },
        { code: 'CM', name: 'Cameroon', rate: 19.25, currency: 'FCFA' },
        { code: 'EG', name: 'Egypt', rate: 14, currency: '£' },
        { code: 'ET', name: 'Ethiopia', rate: 15, currency: 'Br' },
        { code: 'GH', name: 'Ghana', rate: 12.5, currency: '₵' },
        { code: 'KE', name: 'Kenya', rate: 16, currency: 'KSh' },
        { code: 'MG', name: 'Madagascar', rate: 20, currency: 'Ar' },
        { code: 'MU', name: 'Mauritius', rate: 15, currency: '₨' },
        { code: 'MA', name: 'Morocco', rate: 20, currency: 'د.م.' },
        { code: 'MZ', name: 'Mozambique', rate: 17, currency: 'MT' },
        { code: 'NA', name: 'Namibia', rate: 15, currency: '$' },
        { code: 'NG', name: 'Nigeria', rate: 7.5, currency: '₦' },
        { code: 'RW', name: 'Rwanda', rate: 18, currency: 'FRw' },
        { code: 'SN', name: 'Senegal', rate: 18, currency: 'FCFA' },
        { code: 'ZA', name: 'South Africa', rate: 15, currency: 'R' },
        { code: 'TZ', name: 'Tanzania', rate: 18, currency: 'TSh' },
        { code: 'TN', name: 'Tunisia', rate: 19, currency: 'د.ت' },
        { code: 'UG', name: 'Uganda', rate: 18, currency: 'USh' },
        { code: 'ZM', name: 'Zambia', rate: 16, currency: 'ZK' },
        { code: 'ZW', name: 'Zimbabwe', rate: 15, currency: '$' }
      ]
    },
    {
      id: 'middle-east',
      name: 'Middle East',
      countries: [
        { code: 'BH', name: 'Bahrain', rate: 10, currency: '.د.ب' },
        { code: 'IL', name: 'Israel', rate: 17, currency: '₪' },
        { code: 'JO', name: 'Jordan', rate: 16, currency: 'د.ا' },
        { code: 'LB', name: 'Lebanon', rate: 11, currency: 'ل.ل' },
        { code: 'OM', name: 'Oman', rate: 5, currency: 'ر.ع.' },
        { code: 'SA', name: 'Saudi Arabia', rate: 15, currency: 'ر.س' },
        { code: 'AE', name: 'United Arab Emirates', rate: 5, currency: 'د.إ' }
      ]
    },
    {
      id: 'oceania',
      name: 'Oceania',
      countries: [
        { code: 'AU', name: 'Australia', rate: 10, currency: '$' },
        { code: 'FJ', name: 'Fiji', rate: 9, currency: '$' },
        { code: 'NZ', name: 'New Zealand', rate: 15, currency: '$' },
        { code: 'PG', name: 'Papua New Guinea', rate: 10, currency: 'K' },
        { code: 'WS', name: 'Samoa', rate: 15, currency: 'T' },
        { code: 'TO', name: 'Tonga', rate: 15, currency: 'T$' },
        { code: 'VU', name: 'Vanuatu', rate: 15, currency: 'Vt' }
      ]
    }
  ],
  languageToCountry: {
    de: 'DE',
    ro: 'RO',
    en: 'GB',
    sk: 'SK',
    uk: 'UA',
    be: 'BY',
    hu: 'HU',
    bg: 'BG',
    hr: 'HR',
    lt: 'LT',
    et: 'EE',
    fr: 'FR',
    nl: 'NL',
    es: 'ES',
    cs: 'CZ',
    sl: 'SI',
    lv: 'LV',
    it: 'IT',
    pl: 'PL',
    pt: 'PT',
    fi: 'FI',
    ga: 'IE',
    sv: 'SE',
    da: 'DK'
  }
};
